language: go
os: linux-ppc64le
dist: xenial

go_import_path: github.com/pingcap/tidb

go:
  - "1.11"

env:
    - TRAVIS_COVERAGE=0

before_install:  
  # create /logs/unit-test for unit test.
  - sudo mkdir /logs
  - sudo touch /logs/unit-test
  # See https://github.com/golang/go/issues/12933
  - bash gitcookie.sh
script:
#  - make dev
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then make default; fi
